name: "Label Pull Request"
on:
  - pull_request_target
  - push

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@v6
